### ISSUE TITLE
Where is the exe?

### ISSUE THREAD

**Issue by studioyogyog** [scaredyfish/blender-rhubarb-lipsync#1]
Hi - I'm not sure is I should be asking this of you or the creator of Rhubarb...

I've installed your addon in Blender and downloaded and unzipped Rhubarb, but when I come to select the .exe file I can't find one!  There's a batch file, but no .exe.

Do I have to use an older version of Rhubarb?

By the way, I'm currently in the middle of creating a series of tutorials on creating simple automated lipsinc in Blender called Lipsinc for the Lazy in Blender.  If I can get this software working, it will make it obsolete! :S but I don't really mind.  I want to get it working, and do a tutorial on it.

**Comment by studioyogyog** [comment]
Ahh - found the solution!  I was downloading the wrong .zip!

**Comment by Andrew812379** [comment]
Help please i am in the same issue, Tell me how did you pass through?
![gg](https://user-images.githubusercontent.com/57034332/67618112-61b6e300-f7f3-11e9-911e-e3ee03d3261b.PNG)

**Comment by Andrew812379** [comment]
can't find the exe, thats why it omes with that when using the batch instead

**Comment by matthew5678** [comment]
https://github.com/DanielSWolf/rhubarb-lip-sync/releases/tag/v1.10.0
Download the executable for windows here.
