### ISSUE TITLE
Can't enable blender-rhubarb-lipsync-master

### ISSUE THREAD

**Issue by subongo** [scaredyfish/blender-rhubarb-lipsync#10]
When I try to enable the Blender-rhubarb-lipsync-master I get the errors shown in the attached photo
![Can't enable blender-rhubarb-lipsync-master](https://user-images.githubusercontent.com/11732629/55292245-3f392480-53e0-11e9-8084-9388415124ae.jpg)

**Comment by scaredyfish** [comment]
Master has been updated for Blender 2.80, and will no longer work with 2.79. Please use version 1.0.5 from https://github.com/scaredyfish/blender-rhubarb-lipsync/releases

I will try to make this clearer in the documentation.

**Comment by subongo** [comment]
I am still on Blender 2.79.  because  2.80 is not ready yet. So I imagine none of your code will be much use.
I need a version that works with Blender 2.79 please.

**Comment by scaredyfish** [comment]
Version 1.0.5 of the addon works with Blender 2.79.

**Comment by subongo** [comment]
Ok I have found that version and it is enabled in Blender. Thanks for all the help

**Comment by olivierroyo** [comment]
same for me, I could enable the plugin
