### ISSUE TITLE
Error when i press Rhubarb lipsynce in blender 2.8

### ISSUE THREAD

**Issue by matthew5678** [scaredyfish/blender-rhubarb-lipsync#11]
Hello, I get an error when I press rhubarb lipsync in blender 2.8, shown in the screenshot.
  
![pic 1 Rhubarb](https://user-images.githubusercontent.com/2991453/55297382-c361cb00-5425-11e9-8ca1-80922dd237f6.PNG)
![pic 2 rhubarb](https://user-images.githubusercontent.com/2991453/55297385-c8267f00-5425-11e9-8d73-490878686bda.PNG)

**Comment by scaredyfish** [comment]
You set the executable location of Rhubarb lip sync in user preferences?

It looks like the executable is not recognised. Are you able to run rhubarb.exe from the command line?

**Comment by matthew5678** [comment]
Yes, I already set it, the execution location in user preference, and  I am not able to run rhubarb.exe from the command line.

**Comment by scaredyfish** [comment]
This sounds like a problem with Rhubarb Lip Sync, then, rather than a problem with the Blender extension. Perhaps try re-installing it. Other than that, I'm not sure what to suggest.

**Comment by matthew5678** [comment]
Thanks I have found the problem, I used the wrong Executable, it working now thanks.
