### ISSUE TITLE
rhubarb error exec format error in blender 2.79

### ISSUE THREAD

**Issue by roccotitlan** [scaredyfish/blender-rhubarb-lipsync#12]
Hi. Trying to run rhubarb on blender 2.79 but it doesnt work. Ive created a pose library, uploaded a .wav audio file and when pressing Rhubarb lipsync button it pops the error: "OSError: [Errno 8] Exec format error"
![Screenshot from 2019-04-15 21-54-32](https://user-images.githubusercontent.com/49666421/56178826-3ee87e00-5fc9-11e9-8d73-b463c5112ef8.png)

Thanks for your advise

**Comment by scaredyfish** [comment]
Thanks for your report,

What OS are you using?
Is your rhubarb lip sync executable correct in User Preferences?
Does rhubarb lip sync run outside of Blender?
Could you run Blender from the command line, and let me know if there are any additional error messages when you try to run rhubarb lip sync?

**Comment by roccotitlan** [comment]
Im Using Ubuntu 16.04. 
Yes, User Preferences is correct
![Screenshot from 2019-04-16 06-02-43](https://user-images.githubusercontent.com/49666421/56204584-63fee000-600d-11e9-9a4c-0b0f558c21ab.png)
No, rhubarb does not run from command line, no additional  error messages
![Screenshot from 2019-04-16 06-05-18](https://user-images.githubusercontent.com/49666421/56204752-ca83fe00-600d-11e9-939e-e676ac1ead82.png)
No additional error messages when running Blender from command line

**Comment by scaredyfish** [comment]
It sounds like a problem with Rhubarb Lip Sync itself then. I looked up the error, and it may be a compatibility problem between the Rhubarb Lip Sync package and your version of Linux. 

https://askubuntu.com/questions/648555/bash-program-cannot-execute-binary-file-exec-format-error
