### ISSUE TITLE
get error when clicking Run Rhubarb lipsync

### ISSUE THREAD

**Issue by rickcreations** [scaredyfish/blender-rhubarb-lipsync#14]
![Screenshot (32)](https://user-images.githubusercontent.com/50303381/57982982-bf0b6480-7a09-11e9-898e-d5887e98e832.png)
I'm sending some shots of the errors and the blend file.  I thinking I'm confused on which path I'm choosing in the preferences, but it could be something else.
Thank you for your help
Rick
![Screenshot (33)](https://user-images.githubusercontent.com/50303381/57982983-c29eeb80-7a09-11e9-8bb7-3be45868659b.png)
![Screenshot (32)](https://user-images.githubusercontent.com/50303381/57983006-f8dc6b00-7a09-11e9-99c5-af407acca1da.png)

**Comment by rickcreations** [comment]
I'm not sure what file to use as the exe. in the preference because there's no exe. file in the folder.
if I'm supposed to use one of the py. files could you tell me which one. The rhubarb zipped file doesn't work, I keep getting the win32 error when I try to run it
Thank you Rick

**Comment by Muhammad295** [comment]
Did you find the solution?
I am stuck at the same problem for time..., Do reply, Bro.
