### ISSUE TITLE
Rhubarb for Blender not working with Mac OS CATALINA

### ISSUE THREAD

**Issue by Seabat7** [scaredyfish/blender-rhubarb-lipsync#16]
The current version of Rhubarb for Blender 2.0.1 is not compatible with the latest release fo Mac OS, Catalina. Is there a newer version of the Blender addon?

**Comment by scaredyfish** [comment]
That's the latest version at the moment. 

Unfortunately I don't have a Mac so I can't test, but if you let me know what errors you're getting, I'll see what I can do.

**Comment by Seabat7** [comment]
I truly appreciate that!
I re installed the plugin and now it shows up in the panel but is asking for the APP location and the run Rhubarb message is ghosted. 
I’m more than happy to help beta test the Mac side- anything to help others.
I’m hoping to use this for a pilot I’m doing for a children’s series.  
Thanks,
Sam

**Comment by scaredyfish** [comment]
You have downloaded Rhubarb itself from https://github.com/DanielSWolf/rhubarb-lip-sync/releases and unzipped it somewhere? 

You will need to go into user preferences and in the Blender Rhubarb Lip Sync settings point the executable file - not sure what that would be on mac, but probably a file just called 'rhubarb'

**Comment by Seabat7** [comment]
This version worked!!!  Wow- it did an amazing job!!  Thank you for sending this to me!

There’s so many versions out there that the correct version was lost in all the search engines. 

This is going to save my bacon! Thanks again.
Sam

**Comment by scaredyfish** [comment]
Glad to hear it. I'd love to see the results of your pilot when it's done. Good luck!

**Comment by Seabat7** [comment]
I’ll send you a link/ copy when I finish.

**Comment by sohel-oss** [comment]
SIR ,, im trying to fix from last two days rhubarb in my Mac silicon m1 ,, its showing python error and im really so tired.  can you tell me any solution please 

please that and if possible help me please 

<img width="1440" alt="Screen Shot 2022-08-29 at 10 04 28 PM" src="https://user-images.githubusercontent.com/112423069/187268364-670652bf-ccfd-44ac-8700-b7b259ea76cc.png">

**Comment by scaredyfish** [comment]
Where it says 'no such file or directory' - does that file exist? Is there anything in that folder at all?
