### ISSUE TITLE
I'm getting this error message:

### ISSUE THREAD

**Issue by studioyogyog** [scaredyfish/blender-rhubarb-lipsync#2]
RuntimeError: class OBJECT_OT_rhubarb_lipsync, function modal: incompatible return value , str(, Function.result expected a set, not a NoneType)

location: <unknown location>:-1

**Comment by scaredyfish** [comment]
Could you explain more what you are doing when this error occurs? Could you attach a .blend file?

**Comment by studioyogyog** [comment]
By the way I would like to do a shoutout for you in my next tutorial
(should be uploaded on Thursday), which will get more people
interested in your addon, which could lead to help with it.  Is this
something you would want?  This should get around 2000 views and
appear BlenderNation. Would this actually be helpful for you?

**Comment by scaredyfish** [comment]
Yes, that would be great! 

I think this issue is to do with relative file paths, so now I convert paths to absolute. 

Could you download and give it a try?

**Comment by studioyogyog** [comment]
Sure. Will do this evening.

Thanks.

**Comment by studioyogyog** [comment]
Thankyou! this is now working fine!

I've got it working with both the pencil drawn test I showed you, and with
a realistic person from Makehuman.  My Thursday tutorial will now be on
using your plugin with Makehuman.  Thursday is my day off, so I do
tutorials then - it takes me at least a day to make one.

I can send you a script for the intro (I do the tutorial part unscripted)
but I would rather it was not public before the tutorial goes live.  What
is your email?

Should I refer to you as Scaredyfish?

**Comment by scaredyfish** [comment]
I don't need to see the script, and yes you can refer to me as Scaredyfish. Make sure you credit Daniel Wolf, the creator of Rhubarb Lip Sync as well.

**Comment by studioyogyog** [comment]
Sure - that's the plan - and mention Thimbleweed Park as well!

**Comment by studioyogyog** [comment]
Hi - I've been mulling over whether this is too much to ask you, but I
decided to do it anyway.

Can I suggest a simple UI change?

You see, most lipsinc programs name the mouth shapes after the sound
they make rather than the first 8 letters of the alphabet and X.  What
I'm suggesting is where it says
Mouth A:
Mouth B:
Mouth C:
Mouth D:
   etc
in the Blender UI

it should say

Mouth A (MBP):
Mouth B (EE/etc):
Mouth C (E):
Mouth D (AI):
Mouth E (O):
Mouth F (WQ):
Mouth G (FV):
Mouth H (L):
Mouth X (rest):

These are the mouth names on Papagayo, so it will allow people using
that software to easily transition.

Thanks for your fantastic addon,
Mike

**Comment by scaredyfish** [comment]
Not too much at all, those changes make sense to me. I've updated this in master.

**Comment by studioyogyog** [comment]
The video's up!

https://www.youtube.com/watch?v=Nnu7TFTn_W4&t=2s

**Comment by studioyogyog** [comment]
I'm sorry - I messed up.

My first version of the video, as you know, had rather bad sound around the
5 minute mark, so I asked BlenderNation not to post it, then I corrected
the sound, re-uploaded, and then I got into a panic and sent about 5
emails.  He's put it up, but with a rather back-handed message, so it's not
doing as well as I had hoped.

The thing is - your addon is big news!  Up til now, the method for doing
lipsync was Papagayo.  I'm not sure if you've used Papagayo, but I don't
think it actually listens to the soundfile.

What I'd recommend is you post to Blendernation your self - use that
animated mouth video, and a link to your page on Github.  If you choose to
put my tutorial at the bottom of the page - that's up to you.

Otherwise, I will definitely be using your software in my next tutorial,
but it will be a while before I get a chance to make another one.

**Comment by scaredyfish** [comment]
It's all good. These things happen.

**Comment by mahlori** [comment]
Greatings, I need help please, am trying to run rhubarb on blender 2.8 I think I did everything correct but when I press "rhubarb lipsync" I get this message "traceback (most recent call last) 

File "C/users......./appData/Roaming/blender foundation/blender/2.80/ scripts/add-ons/blender-rhubarb-lipsync-master/op_blender_rhubab.py",line 223, in invoke stdout=subprocess.PIPE, universal_newlines=true

Did I do anything wrong
