### ISSUE TITLE
Grease Pencil problem

### ISSUE THREAD

**Issue by Dostojetski** [scaredyfish/blender-rhubarb-lipsync#20]
Hiya!

3.0.1 works, awesome!

I followed the tutorial and got a working animation https://photos.app.goo.gl/iNHVWmNCa9DURXca8

Problem is using 9 bones for each mouthshape(using grease pencil) the GP dots remain even when scale is zero. So I need to do it with one bone, hooking up time offset. I made the poselib and tested each pose, the bone swaps it perfectly between mouth shapes but when I run Rhubarb lipsync, the poses are not switching. I get the keyframes in action editor but the mouth is not animated 🤒 

Im wondering if Rhubarb requires the 9 bones to work or where am I going wrong? Also, if scaling is what makes rhubarb function?

**Comment by scaredyfish** [comment]
There's nothing that requires 9 bones or scaling in particular. The system just applies the poses as they are in the library, no matter how many bones there are. If you're able to share a .blend file I can take a look. 

I haven't specifically tested with Grease Pencil, but if it works with all the other mouth shapes, it seems odd that there would be only one that doesn't work.

**Comment by Dostojetski** [comment]
The grease pencil frame is pulled with a custom property and its not getting triggered via rhubarb. Though I am pretty sure there are workarounds, I'm not skilled enough to get it done but if you can confirm this, it would be great so I know to press on.

Attached a save file with the grease pencil prepped, just needs a script and an audio file
[AnimationTest4Mouth.zip](https://github.com/scaredyfish/blender-rhubarb-lipsync/files/4563560/AnimationTest4Mouth.zip)

**Comment by Dostojetski** [comment]
Closing this, I was an idiot... got it to work just fine by making one bone dependant one another bone and moving that instead.

Rhubarb is really awesome!
