### ISSUE TITLE
Nothing happens when the button is clicked.

### ISSUE THREAD

**Issue by leouchaly** [scaredyfish/blender-rhubarb-lipsync#21]
Good afternoon. You can help me, I did everything, and at the end when I click on the Rhubarb lipsync button, nothing happens. The bones are all highlighted, the text is loaded, and the audio is also loaded.
I thought something was wrong with my project, then I downloaded yours, the same thing. Thank you for your time.

**Comment by leouchaly** [comment]
[https://yadi.sk/i/68V88y-0SpPfoQ](url)

**Comment by leouchaly** [comment]
https://yadi.sk/i/68V88y-0SpPfoQ

**Comment by scaredyfish** [comment]
Hi, could you please open the console, as described at https://github.com/scaredyfish/blender-rhubarb-lipsync#troubleshooting and provide a paste or screenshot of any error messages.

**Comment by AnthonySouls** [comment]
Can anyone help me with this?

![Capturar](https://user-images.githubusercontent.com/41519295/96603889-dd465580-12ca-11eb-8fbc-3e459206e0e6.PNG)

**Comment by AnthonySouls** [comment]
I think I'm having the same mistake as him. Nothing happens when the button is clicked, when I open the console this error appears.

**Comment by scaredyfish** [comment]
@AnthonySouls That error seems to be complaining about a missing file, specifically "%AppData%\Blender Foundation\Blender\2.83\scripts\addons\blender-rhubarb-lipsync\bin\res\sphinx\acoustic-model\mdef" This file should be installed with the addon, could you check if it exists? 

Removing the blender rhubarb lip sync addon entirely, and then re-installing it may help, or just pulling the "mdef" file out of the zip and replacing it.

**Comment by Mataconarte-art** [comment]
Hello. I am having the same issue. I do not know if it is because I am using a different audio file than a .wav which seems to be what everyone is using, but I do get this error code when I click on the Lipsync button.

![Screen Shot 2020-12-17 at 7 18 30 AM](https://user-images.githubusercontent.com/76172523/102507174-cb6a0000-4038-11eb-8e03-741dd32bc0d6.png)

**Comment by scaredyfish** [comment]
I suspect all these issues are installation problems. I have added installation instructions at https://github.com/scaredyfish/blender-rhubarb-lipsync/#installation

If you continue to have problems, please open another issue.

**Comment by fengqingyuns** [comment]
> @AnthonySouls该错误似乎是在抱怨缺少文件，特别是“%AppData%\Blender Foundation\Blender\2.83\scripts\addons\blender-rhubarb-lipsync\bin\res\sphinx\acoustic-model\mdef”这个文件应该和插件一起安装，你能检查它是否存在吗？
> 
> 完全删除搅拌机大黄唇形同步插件，然后重新安装它可能会有所帮助，或者只是将“mdef”文件从 zip 中拉出并替换它。

替换了也不行，用其他版本也不行，换个电脑就可以了，难道和电脑的配置有关系？
