### ISSUE TITLE
Can't install blender rhubarb lipsync on Blender 2.82

### ISSUE THREAD

**Issue by SandroGiorgadze** [scaredyfish/blender-rhubarb-lipsync#23]
Hello,

I've downloaded the blender rhubarb lipsync addon and trying to install it in Blender version 2.82, on Windows 10 (64 bit). I've downloaded Version 3.0.1, which bundles Rhubarb Lip Sync by Daniel S. Wolf. 

I watched and followed the video by YOGYOG, where they're installing the rhubarb.exe via user preferences (though in blender 2.79). rhubarb.exe now is located in bin folder, but when I open the Blender preferences and try to install it, rhubarb.exe is not visible... 

https://user-images.githubusercontent.com/77115511/103917565-9a726d80-50c2-11eb-8ead-c36ac5ea66a5.mp4

Please let me know what I'm doing wrong. I've attached the screen recording just in case...   If this is not an appropriate place to ask this question, please direct me to the support, as I wasn't able to find any other support sections elsewhere. 

Thanks in advance

**Comment by scaredyfish** [comment]
Hi, to install addons in Blender, you don't need to unzip the file first. Just select the zip file, that should install everything where it needs to be. Because rhubarb is included, the exe should already be set up correctly in user preferences.
