### ISSUE TITLE
Button Greyed Out (Rhubarb lipsync) - Blender 2.83, 2.92

### ISSUE THREAD

**Issue by sahilarch** [scaredyfish/blender-rhubarb-lipsync#25]
Nothing shows up in "info" or console, tried Rhubarb v1.10, and included 3.0.1, no luck

**Comment by sahilarch** [comment]
did not go into pose mode!!!! please put up a information/warning about that, thanks

**Comment by scaredyfish** [comment]
Thanks for letting me know. I'll consider adding a warning about that.
