### ISSUE TITLE
Exporting Blender Model with Rhubarb LipSync

### ISSUE THREAD

**Issue by mshafieluru** [scaredyfish/blender-rhubarb-lipsync#26]
Hello,

Is it possible to export a blender model with lip sync added to it as a GLTF file ?

Can I pass the Sound File and Dialog File from a different path to GLTF file

Please let me know the steps.

Regards
Shafi

**Comment by scaredyfish** [comment]
Hi Shafi,

Once the lip sync is added, it's just normal Blender keyframes, so how it's exported to GLTF is not part of this addon. I'm not familiar with how the GLTF export works, so I'm sorry I don't think I can help.
