### ISSUE TITLE
Shape keys

### ISSUE THREAD

**Issue by Marte2007** [scaredyfish/blender-rhubarb-lipsync#28]
Is it possible to use this addon with a model using shape keys for mouth animation instead of a pose library?

**Comment by scaredyfish** [comment]
No, the addon is based around the use of a pose library. If you want to use shape keys, you can set up a simple rig with bones to control your shape keys, and create a pose library based on that.

There's a tutorial covering that case (not made by me) at https://youtu.be/vZVtUEEssxQ
