### ISSUE TITLE
Error Message Runtime

### ISSUE THREAD

**Issue by dltv** [scaredyfish/blender-rhubarb-lipsync#3]
Hello, 
I want to thank you in advance for working on this lipsync project. I am getting an error when I hit the Rhubarb lipsync button in the Blender Addon.
RuntimeError: class OBJECT_OT_rhubarb_lipsync, function modal: incompatible return value , str(, Function.result expected a set, not a NoneType)
location: <unknown location>:-1

I noticed that there is a closed issue with a similar problem. How was it resolved?

Thank you in advance,

Best, 
David

**Comment by scaredyfish** [comment]
I think this can happen when the sound file is not recognised in Rhubarb lip sync. Currently only .wav files are supported, so this error occurs if you try to use an MP3 or something else.

If that's not it, you can get more detailed info on what's going on in the system console (Window -> toggle system console). 

I'll keep this issue open, as the extension ought to handle these errors more gracefully.

**Comment by dltv** [comment]
Thanks for the quick response. I am in fact using a .wav file, but according to the system console, the file is bellow 16000 hz. I will try another audio file and get back to you with an update.
{ "type": "failure", "reason": "Error processing file \"C:\\Users\\overh\\Documents\\lipsync\\OSR_us_000_0030_8k.wav\".\nError detecting segments of speech.\nUpsampling not supported. Input sample rate must not be below 16000Hz.", "log": { "level": "Fatal", "message": "Application terminating with error: Error processing file \"C:\\Users\\overh\\Documents\\lipsync\\OSR_us_000_0030_8k.wav\".\nError detecting segments of speech.\nUpsampling not supported. Input sample rate must not be below 16000Hz." } }
RuntimeError: cla

**Comment by dltv** [comment]
So I tried a new .wav file. Now the console is giving me this note that seems to be related to the sample format. Is there a recommended setting for the audio.?:
location: <unknown location>:-1
{ "type": "start", "file": "C:\\Users\\overh\\Downloads\\Recording.wav", "log": { "level": "Info", "message": "Application startup. Input file: \"C:\\Users\\overh\\Downloads\\Recording.wav\"." } }
{ "type": "failure", "reason": "Error processing file \"C:\\Users\\overh\\Downloads\\Recording.wav\".\nCould not open sound file \"C:\\Users\\overh\\Downloads\\Recording.wav\".\nUnsupported sample format: 32-bit PCM.", "log": { "level": "Fatal", "message": "Application terminating with error: Error processing file \"C:\\Users\\overh\\Downloads\\Recording.wav\".\nCould not open sound file \"C:\\Users\\overh\\Downloads\\Recording.wav\".\nUnsupported sample format: 32-bit PCM." } }
RuntimeError: class OBJECT_OT_rhubarb_lipsync, function modal: incompatible return value , str(, Function.result expected a set, not a NoneType)

location: <unknown location>:-1

location: <unknown location>

**Comment by scaredyfish** [comment]
Not that I know of.  I can't see anything mentioned on the Rhubarb lip sync page. Maybe open an issue there: https://github.com/DanielSWolf/rhubarb-lip-sync

**Comment by dltv** [comment]
Well. I converted the file to .wav(Microsoft) signed 16 bit  PCM in Audacity, and it works. 
I will keep testing, but this seams to be the way I will prep the files. Looking forward to making stuff with Rhubarb. Thank you very much for making it!
Best, 
David
