### ISSUE TITLE
Im having an issue Can someone help out? 

### ISSUE THREAD

**Issue by YTMPRo** [scaredyfish/blender-rhubarb-lipsync#30]
Python: Traceback (most recent call last):
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-rhubarb-lipsync-master\op_blender_rhubarb.py", line 122, in invoke
    os.chmod(executable, 0o744)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\chris\\Desktop\\Design\\3D\\Blender\\Sketches\\Lip Sync\\rhubarb.exe'

location: <unknown location>:-1

**Comment by scaredyfish** [comment]
Try installing the latest release at https://github.com/scaredyfish/blender-rhubarb-lipsync/releases 

Feel free to re-open the issue if you still get the error.
