### ISSUE TITLE
can some1 help me with rhubarb lipsync in blender It gives out error

### ISSUE THREAD

**Issue by CoyCatBlack** [scaredyfish/blender-rhubarb-lipsync#31]
Python: Traceback (most recent call last):
  File "C:\Users\liaqu\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-rhubarb-lipsync-master\op_blender_rhubarb.py", line 122, in invoke
    os.chmod(executable, 0o744)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\liaqu\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons/blender-rhubarb-lipsync/bin/rhubarb.exe'

location: <unknown location>:-1

it give error like this please help me

**Comment by scaredyfish** [comment]
Does the file 'C:\Users\liaqu\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons/blender-rhubarb-lipsync/bin/rhubarb.exe' exist?

This file should have been installed with the addon. If it's not there, you can install rhubarb separately and set the exe path in addon settings.
