### ISSUE TITLE
Rhubarb can't be installed in Blender 3.0

### ISSUE THREAD

**Issue by Endertainer007** [scaredyfish/blender-rhubarb-lipsync#32]
So I tried to install the rhubarb addon but it gives me this error instead.
![image](https://user-images.githubusercontent.com/57242521/144710371-3b8b4d31-9ba6-4de4-9bad-476d5c896b06.png)
I'm using Blender 3.0.

**Comment by scaredyfish** [comment]
Thanks for letting me know. Looks like there was a minor API change - it should be an easy fix, I'll try to get to it soon.

**Comment by Endertainer007** [comment]
OK. Let me know when a patch is release.

**Comment by ShockBock** [comment]
Thanks for your efforts, scaredyfish. This could be a 3.0-wide problem, as I can't install Rhubarb into the new update either. I think this error message is pretty much the same as experienced by Endertainer

![Rhub_error](https://user-images.githubusercontent.com/95683548/145004123-c33e97ce-8bf9-4e2d-b413-4c2ed3987b29.jpg)

**Comment by nicholasekubi** [comment]
Thank you soo much for this

**Comment by masonj19** [comment]
You can fix the error by changing line 13 in `prefs_blender_rhubarb.py` from
`default=bpy.utils.user_resource('SCRIPTS', "addons") + '/blender-rhubarb-lipsync/bin/rhubarb' + ('.exe' if system() == 'Windows' else '')`
to
`default=bpy.utils.user_resource('SCRIPTS', path="addons") + '/blender-rhubarb-lipsync/bin/rhubarb' + ('.exe' if system() == 'Windows' else '')`

The necessary change is adding `path=` to the second argument of `bpy.utils.user_resource`.

The 2nd & 3rd args in bpy.utils.user_resource were changed to keyword only arguments as noted here: https://wiki.blender.org/wiki/Reference/Release_Notes/3.0/Python_API#Blender_3.0:_Python_API

There may still be other issues. I haven't done much testing with it yet.

**Comment by Endertainer007** [comment]
> default=bpy.utils.user_resource('SCRIPTS', path="addons") + '/blender-rhubarb-lipsync/bin/rhubarb' + ('.exe' if system() == 'Windows' else '')

I tried adding the patch and it works.
![image](https://user-images.githubusercontent.com/57242521/145749579-869fed8c-77c9-4069-a8ea-e34e286967ca.png)

**Comment by ShockBock** [comment]
Was able to get Rhubarb installed thanks to masonj19's fix. Good work sir!

Not tested the plugin beyond successful installation yet, but this looks promising

**Comment by ShockBock** [comment]
![Rhubarb post install error](https://user-images.githubusercontent.com/95683548/146069923-77d2e00f-fafb-4070-b755-6648e9147838.jpg)

This is the error message I got when I test-ran the post-patch (c/o mason's fixj19's fix) Rhubarb just now to do some lip synching. Looks like we're not out of the woods yet. I'm running Blender on Ubuntu (Linux) in case that makes a difference

**Comment by Endertainer007** [comment]
> This is the error message I got when I test-ran the post-patch (c/o mason's fixj19's fix) Rhubarb just now to do some lip synching. Looks like we're not out of the woods yet. I'm running Blender on Ubuntu (Linux) in case that makes a difference

masonj19 fixes were meant for the windows version. Maybe that's why it doesn't work. Also, do you have an issue with the unmodified version?

**Comment by scaredyfish** [comment]
Thanks for the fix @masonj19, this fix is now incorporated into the latest release at https://github.com/scaredyfish/blender-rhubarb-lipsync/releases

@ShockBock I think you have a different issue. The error message says it can't find the Rhubarb binary - this is installed in the release linked above, but won't be there if you just cloned the repo.

**Comment by ShockBock** [comment]
Great work folks. Have reinstalled, this time with Rhubarb 3.0.2 for Linux and have generated some lip syncing key-frames using the tool. Seems to be back up and working 100%. Thanks for your efforts!

I've been key-framing for dialogue the old fashioned way over the past couple of days whilst Rhubarb was unavailable. Let's just say I'm appreciating the plug-in, now that it's working again, more than ever!
