### ISSUE TITLE
RHUBARB ADDON NOT WORKING BLENDER 3.0

### ISSUE THREAD

**Issue by nicholasekubi** [scaredyfish/blender-rhubarb-lipsync#33]
The addon is lovely and worked quite well in blender 2.9 but it does run into errors when we move over to 3.0. Could you please help me. I couldnt figure out how to add pictures but someone else did post this exact issue.

**Comment by scaredyfish** [comment]
This is fixed now. Install the latest release at https://github.com/scaredyfish/blender-rhubarb-lipsync/releases
