### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by VThomas78** [scaredyfish/blender-rhubarb-lipsync#35]
Hi !

When i launch the script i have this note. 
what can i do ? :) 

Thanks !
![2022-01-26 13_07_37-Blender Info Log](https://user-images.githubusercontent.com/98462672/151160678-634eeeca-d30e-4b51-b2ea-5918613fa412.png)

**Comment by scaredyfish** [comment]
It looks like you cloned the repository, which does not include all needed files. Please use a release from https://github.com/scaredyfish/blender-rhubarb-lipsync/releases
