### ISSUE TITLE
Anyone else having this kind of error message?

### ISSUE THREAD

**Issue by desperado30** [scaredyfish/blender-rhubarb-lipsync#37]
<img width="672" alt="rhubarberror" src="https://user-images.githubusercontent.com/99550245/153718745-bbfebc62-eb25-4a25-bac6-25e7ffac626e.png">

I have tried installing rhubarb and blender addon again and I have tried different wav files but nothing seems to work. Please help me I need this to work so badly :(( Thank you!!

**Comment by fengqingyuns** [comment]
I am also such a mistake, but there will be no error on another computer. Strange, it should be a bug
