### ISSUE TITLE
没有任何反应

### ISSUE THREAD

**Issue by fengqingyuns** [scaredyfish/blender-rhubarb-lipsync#39]
点击生成的时候没有任何反应

**Comment by scaredyfish** [comment]
Please follow the troubleshooting steps in the documentation.

**Comment by fengqingyuns** [comment]
> Please follow the troubleshooting steps in the documentation.

Error!!!
{ "type": "start", "file": "C:\\Users\\\u674e\u6d9b\\Desktop\\1.wav", "log": { "level": "Info", "message": "Application startup. Input file: C:\\Users\\\u674e\u6d9b\\Desktop\\1.wav." } }
{ "type": "progress", "value": 0.00, "log": { "level": "Trace", "message": "Progress: 0%" } }
{ "type": "progress", "value": 0.01, "log": { "level": "Trace", "message": "Progress: 1%" } }
{ "type": "progress", "value": 0.02, "log": { "level": "Trace", "message": "Progress: 2%" } }
{ "type": "progress", "value": 0.03, "log": { "level": "Trace", "message": "Progress: 3%" } }
{ "type": "progress", "value": 0.04, "log": { "level": "Trace", "message": "Progress: 4%" } }
{ "type": "progress", "value": 0.05, "log": { "level": "Trace", "message": "Progress: 5%" } }
{ "type": "progress", "value": 0.06, "log": { "level": "Trace", "message": "Progress: 6%" } }
