### ISSUE TITLE
ERROR!!!

### ISSUE THREAD

**Issue by fengqingyuns** [scaredyfish/blender-rhubarb-lipsync#40]
Error!!!
{ "type": "start", "file": "C:\\Users\\\u674e\u6d9b\\Desktop\\1.wav", "log": { "level": "Info", "message": "Application startup. Input file: C:\\Users\\\u674e\u6d9b\\Desktop\\1.wav." } }
{ "type": "progress", "value": 0.00, "log": { "level": "Trace", "message": "Progress: 0%" } }
{ "type": "progress", "value": 0.01, "log": { "level": "Trace", "message": "Progress: 1%" } }
{ "type": "progress", "value": 0.02, "log": { "level": "Trace", "message": "Progress: 2%" } }
{ "type": "progress", "value": 0.03, "log": { "level": "Trace", "message": "Progress: 3%" } }
{ "type": "progress", "value": 0.04, "log": { "level": "Trace", "message": "Progress: 4%" } }
{ "type": "progress", "value": 0.05, "log": { "level": "Trace", "message": "Progress: 5%" } }
{ "type": "progress", "value": 0.06, "log": { "level": "Trace", "message": "Progress: 6%" } }

Error!!!
{ "type": "start", "file": "C:\\Users\\\u674e\u6d9b\\Desktop\\1.wav", "log": { "level": "Info", "message": "Application startup. Input file: C:\\Users\\\u674e\u6d9b\\Desktop\\1.wav." } }
{ "type": "progress", "value": 0.00, "log": { "level": "Trace", "message": "Progress: 0%" } }
{ "type": "progress", "value": 0.01, "log": { "level": "Trace", "message": "Progress: 1%" } }
{ "type": "progress", "value": 0.02, "log": { "level": "Trace", "message": "Progress: 2%" } }
{ "type": "progress", "value": 0.03, "log": { "level": "Trace", "message": "Progress: 3%" } }
{ "type": "progress", "value": 0.04, "log": { "level": "Trace", "message": "Progress: 4%" } }
{ "type": "progress", "value": 0.05, "log": { "level": "Trace", "message": "Progress: 5%" } }
{ "type": "progress", "value": 0.06, "log": { "level": "Trace", "message": "Progress: 6%" } }

Error!!!

**Comment by fengqingyuns** [comment]
Changing to 3.0.1 also reports an error 。Error!!!
{ "type": "start", "file": "C:\\Users\\\u674e\u6d9b\\Desktop\\202204022124.wav", "log": { "level": "Info", "message": "Application startup. Input file: \"C:\\Users\\\u674e\u6d9b\\Desktop\\202204022124.wav\"." } }
{ "type": "progress", "value": 0.00, "log": { "level": "Trace", "message": "Progress: 0%" } }
{ "type": "progress", "value": 0.01, "log": { "level": "Trace", "message": "Progress: 1%" } }
{ "type": "progress", "value": 0.02, "log": { "level": "Trace", "message": "Progress: 2%" } }
{ "type": "progress", "value": 0.03, "log": { "level": "Trace", "message": "Progress: 3%" } }
{ "type": "progress", "value": 0.04, "log": { "level": "Trace", "message": "Progress: 4%" } }
{ "type": "progress", "value": 0.05, "log": { "level": "Trace", "message": "Progress: 5%" } }
{ "type": "progress", "value": 0.06, "log": { "level": "Trace", "message": "Progress: 6%" } }
{ "type": "log", "log": { "level": "Error", "message": "\"acmod.c\", line 83: Folder 'C:\\Users\\\u674e\u6d9b\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\blender-rhubarb-lipsync\\bin\\res\\sphinx\\acoustic-model' does not contain acoustic model definition 'mdef'" } }
{ "type": "failure", "reason": "Error processing file \"C:\\Users\\\u674e\u6d9b\\Desktop\\202204022124.wav\".\nError performing speech recognition via PocketSphinx tools.\nError creating speech decoder.", "log": { "level": "Fatal", "message": "Application terminating with error: Error processing file \"C:\\Users\\\u674e\u6d9b\\Desktop\\202204022124.wav\".\nError performing speech recognition via PocketSphinx tools.\nError creating speech decoder." } }

Error!!!

**Comment by fengqingyuns** [comment]
<img width="850" alt="1648910485(1)" src="https://user-images.githubusercontent.com/31096725/161388437-c5dd9f30-240e-45bb-95de-8af3a2b875ce.png">

**Comment by fengqingyuns** [comment]
Upgrading blender to 3.0 still reports an error, but there is this file in disk C. It also reports an error if it is replaced, but there is no error on another computer

**Comment by fengqingyuns** [comment]
I hope the boss can solve it. Thank you

**Comment by fengqingyuns** [comment]
I found the reason. Haha, it's not that there is no file. It's estimated that there is a problem with the code. It's not found. Haha, it's ready to run

**Comment by ajpintos** [comment]
I've tried to make it work in Blender 3.1 and it doesn't work... the Lip Sync button doesn't do anything...
