### ISSUE TITLE
Don´t work in Blender 3.1

### ISSUE THREAD

**Issue by ajpintos** [scaredyfish/blender-rhubarb-lipsync#41]
I have installed the version blender-rhubarb-lipsync-windows-3.0.2 but in blender 3.1 the button of Rhubarb Lipsync to start the lipsyn do nothing.... :(

**Comment by fengqingyuns** [comment]
You read the wrong information on the console

**Comment by aknittel1** [comment]
"You read the wrong information on the console" - What does that mean?

**Comment by aknittel1** [comment]
Does it have an issue with Blender 3.1 or not, and are you fixing it if it DOES have an issue?

**Comment by scaredyfish** [comment]
I have not tested the addon on 3.1 yet. Can you open the console (Window->Toggle System Console) and let me know any messages/errors it shows.

**Comment by ajpintos** [comment]
I´ve tested and works!! The problem was that i´ve used a mp3 file instead
of a wav... When you use a mp3 file the plugin do nothing... but didn´t
show any error... just do nothing...

**Comment by fengqingyuns** [comment]
> 我还没有在 3.1 上测试过插件。您能否打开控制台（窗口-> 切换系统控制台）并让我知道它显示的任何消息/错误。

Can you send a picture of the mouth shape?

**Comment by ajpintos** [comment]
Better, i can sent a video https://somup.com/c3flVkOFoZ

**Comment by ajpintos** [comment]
Exist a way to bake the lipsync animation to export to GLTF?

**Comment by fengqingyuns** [comment]
Can you send a picture of the mouth shape?

**Comment by KaijuKoder** [comment]
> I´ve tested and works!! The problem was that i´ve used a mp3 file instead of a wav... When you use a mp3 file the plugin do nothing... but didn´t show any error... just do nothing... El lun, 11 abr 2022 a las 19:48, scaredyfish ***@***.***>) 

I had a similar problem with an m4a file. The console window warns it must be a wav or ogg. A warning hint instead of just a gray button would be nice because many new or returning users seem to get tripped up by this.
