### ISSUE TITLE
python : Traceback (most recent call last)

### ISSUE THREAD

**Issue by nik91791** [scaredyfish/blender-rhubarb-lipsync#47]
Python: Traceback (most recent call last):
  File "C:\Users\asus\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-rhubarb-lipsync-master\op_blender_rhubarb.py", line 122, in invoke
    os.chmod(executable, 0o744)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\asus\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons/blender-rhubarb-lipsync/bin/rhubarb.exe'

location: <unknown location>:-1

this comes when I press Rhubarb lipsync. plz give solution

**Comment by TheDirtDen** [comment]
https://github.com/scaredyfish/blender-rhubarb-lipsync/issues/46

download windows version 3.0.2   its in there :)
