### ISSUE TITLE
Can I use it to make an animation on Youtube?

### ISSUE THREAD

**Issue by honsedal** [scaredyfish/blender-rhubarb-lipsync#48]
This is not issue. I want to know lisence. I can't find lisence in the read me. 

1. Can I use it to make a video to upload on YouTube? Does it matter if I make a profit from the advertisement?

2. Don't you have any plans to officially release it in the blender market?

**Comment by scaredyfish** [comment]
1. Yes, you can use it for whatever you like. 
2. No plans at this time
