### ISSUE TITLE
How can I fix this error?

### ISSUE THREAD

**Issue by IamaGitUser1** [scaredyfish/blender-rhubarb-lipsync#57]
Python: Traceback (most recent call last):
  File "C:\Users\mholl\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-rhubarb-lipsync-master\op_blender_rhubarb.py", line 122, in invoke
    os.chmod(executable, 0o744)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\mholl\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons/blender-rhubarb-lipsync/bin/rhubarb.exe'

**Comment by TheDirtDen** [comment]
https://github.com/scaredyfish/blender-rhubarb-lipsync/issues/46

download windows version 3.0.2   its in there :)
