### ISSUE TITLE
Rhubarb lipsync dont open in Blender 3.6.2

### ISSUE THREAD

**Issue by GrimHunk** [scaredyfish/blender-rhubarb-lipsync#62]
I installed Rhubard lipsync addon in Blender 3.6.2, his menu will be created in Data, but there nothing, I cant something choose there. I use this addon 1 years ago, but now its dont work. I tryed delete it and reinstal but its dont work. What should I do?
 
![Blender error](https://github.com/scaredyfish/blender-rhubarb-lipsync/assets/143292957/578d3a24-1005-40ad-ba34-4399f6a87a0f)

**Comment by ramzapr** [comment]
same thing nothing slide with the arrow down in the right tab

**Comment by GrimHunk** [comment]
I noticed that this issue only appears in the new version of Blender. Therefore, I found only 2 solutions to the problem: rewrite the addon code for the new version of Blender or install the old version of Blender. However, I'm not a programmer and I don't know how to write addon code, so I could only install Blender 3.4 and the addon worked for me.
