### ISSUE TITLE
Rhubarb processes to 99% and stops.

### ISSUE THREAD

**Issue by BossClaw** [scaredyfish/blender-rhubarb-lipsync#7]
I open up the Blender Console and click "Rhubarb Lipsync" and watch the progress update until 99% and then it stops.

Outside of Blender I ran Rhubarb lipsync on the same audio file with no problem so it's likely the "all done" mesg that Rhubarb sends isn't being received by Blender, so Blender sits and waits.

I'm looking into the code to see if I can find anything beween the newest Rhubarb Version and this Addon, but I'm new to Python and don't expect to figure it out.

**Comment by BossClaw** [comment]
I added some extra mesgs to the progress to hopefully see what it's getting and when it hits 99%, there's no more progress and only ever a return type of "None" which prevents the next stage from happening.
![image](https://user-images.githubusercontent.com/6304758/48459242-6d9ec600-e797-11e8-8fd0-49a1b21e269d.png)

**Comment by scaredyfish** [comment]
Could you try the release I just uploaded with a possible fix: https://github.com/scaredyfish/blender-rhubarb-lipsync/releases/download/1.0.4/blender-rhubarb-lipsync.zip

**Comment by BossClaw** [comment]
Trying it right now, will let you know ASAP

**Comment by BossClaw** [comment]
Bingo!  That did it.
Got to 99% then processed the Mouthcues and filled my timeline with keyframes!

![image](https://user-images.githubusercontent.com/6304758/48459922-4b5a7780-e79a-11e8-844b-f7d30a6300ac.png)
