### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by iconnorthomas** [scaredyfish/blender-rhubarb-lipsync#8]
I downloaded the zip file here and tried to run the addon on my blender file, however I keep getting a Import Error. The message reads:

> Traceback (most recent call last):
> File "C:\Program Files\Belnder Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
> mod =__import__(module_name)
> File "C:\Program Files\Belnder Foundation\Blender\2.79\scripts\addons\blender-rhubarb-lipsync-master\__init__.py", line 27, in <module>
> from . import op_blender_rhubarb, pnl_blender_rhubarb, prefs_blender_rhubarb
> File "C:\Program Files\Belnder Foundation\Blender\2.79\scripts\addons\blender-rhubarb-lipsync-master\op_blender_rhubarb.py", line 7, in <module>
> import select
> ImportError: DLL load failed: %1 is not a valid Win 32 application.

I am really hoping you can help me out! Thank you so much.

**Comment by scaredyfish** [comment]
Hi, it looks like you may need to set the location of the Rhubarb Lip Sync executable in the user preferences of the addon.
