### ISSUE TITLE
Rhubarb Lipsync not Compatible with bLender 2.8

### ISSUE THREAD

**Issue by matthew5678** [scaredyfish/blender-rhubarb-lipsync#9]
Hello, Thanks for your Support. I tried installing the Rhubarb LipSync for blender 2.8, but an error occurs, it says Upgrade to blender 2.8 Required, please, will you be Supporting the upgrade of rhubarb lipsync to blender 2.8

**Comment by scaredyfish** [comment]
Latest version supports 2.8
